### ISSUE TITLE
Flutter 3.13.1 support

### ISSUE THREAD

**Issue by J-Nokwal** [igormidev/youtube_shorts#2]
Require Flutter 3.13.1 support

**Comment by J-Nokwal** [comment]
The current Dart SDK version is 3.1.0.

Because test_app depends on youtube_shorts any which requires SDK version >=3.2.0 <4.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try using the Flutter SDK version: 3.16.9. 


But I dont want to change my version.
any possibility this could run on my version.

**Comment by igormidev** [comment]
Wow, man! So sorry for the time to replying 🙏
Github did not notified me that someone had opened an issue..

I fixed the problem you related in [version 4.0.0](https://pub.dev/packages/youtube_shorts/changelog).
(Also introduced ads possibility :D)

Please update your dependency and let me now if the problem is now resolved. I'll stay in wait for further updates.

**Comment by igormidev** [comment]
Closing issue due to lack of response

**Comment by J-Nokwal** [comment]
ok thanks
